// Bucketlist ActionTypes
export const SET_BUCKETLIST_TOTAL = 'SET_BUCKETLIST_TOTAL';
export const STORE_BUCKETLISTS = 'STORE_BUCKETLISTS';
export const SET_BUCKETLIST_SEARCH_TERM = 'SET_BUCKETLIST_SEARCH_TERM';
export const SET_BUCKETLIST_CURRENT_PAGE = 'SET_BUCKETLIST_CURRENT_PAGE';

// Items ActionTypes
export const SET_ITEM_TOTAL = 'SET_ITEM_TOTAL';
export const STORE_BUCKETLIST_ITEMS = 'STORE_BUCKETLIST_ITEMS';
export const SET_ITEM_SEARCH_TERM = 'SET_ITEM_SEARCH_TERM';
export const SET_ITEM_CURRENT_PAGE = 'SET_ITEM_CURRENT_PAGE';

// Authentication
export const STORE_ACCESSTOKEN = 'STORE_ACCESSTOKEN';
